config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  ## 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about" #少し変更しました。headerボタンのため
    get 'addresses/index'
    get 'addresses/edit'
    resources :items, only: [:index, :show] do
      collection do
        get 'genre_search_result'
      end
    end
    # マイページ
    get "customers/my_page" => "customers#show"
    # 退会
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    # 情報編集
    get   "customers/information/edit" => "customers#edit"
    patch "customers/information"      => "customers#update"
    # 配送先
    resources :addresses, except: [:show]
    
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'destroy_all', on: :collection
    end
    
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'thanks'
        get 'thanks'
      end
    end
  end

  ## 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 【ウッチャン追加】アソシエーション
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # 【ウッチャン追加】アソシエーション

  # customerの配送先
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :image

    # 【ウッチャン追加】
    has_many :cart_items, dependent: :destroy
    # 【ウッチャン追加】
  
  enum status: { on_sale: 0, off_sale: 1 }#販売ステータス用enum

  with_options presence: true do
    validates :name
    validates :detail
    validates :price_without_tax
    validates :is_active
    validates :genre_id, presence: true
    validates :image
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, deposit_completed: 1, in_making: 2, preparing_for_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { making_unable: 0, waiting_for_making: 1, in_making: 2, making_completed: 3, }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  # controller/concearns/admin_authenticate.rbから
  include AdminAuthenticate
  def top
    # 10行まで
    @orders = Order.includes(:customer, :order_details).order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を登録しました"
    else
      render :new
    end
  end


  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品を更新しました"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :detail, :price_without_tax, :status, :image, :genre_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def order_params
    params.require(:order).permit(:status)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.includes(:item)
  end

  def update 
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    
    if @order.update(order_params)
      if @order.status == "deposit_completed"
        @order_details.update_all(making_status: "waiting_for_making")
      end
    end
    
    redirect_to admin_order_path(@order)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# concerns/adminなどを使いますので、beforeaction
  protected

  def after_sign_in_path_for(resource)
    resource.is_a?(Admin) ? admin_root_path : root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin || resource_or_scope.is_a?(Admin)
      new_admin_session_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
  added = [
    :last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :phone_number
    ]
    devise_parameter_sanitizer.permit(:sign_up, keys: added)
    devise_parameter_sanitizer.permit(:account_update, keys: added)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3 class="mb-4 bg-light p-2 border d-inline-block">注文履歴詳細</h3>

      <div class="row">
        <div class="col-md-7 mb-4">
          <table class="table table-borderless table-sm">
            <tr>
              <th style="width: 30%;">購入者</th>
              <td>
                <%= link_to admin_customer_path(@order.customer_id) do %>
                  <%= @order.customer.last_name %> <%= @order.customer.first_name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <th>配送先</th>
              <td>
                〒<%= @order.postal_code %> <%= @order.address %><br>
                <%= @order.name %>
              </td>
            </tr>
            <tr>
              <th>支払方法</th>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
            <tr>
              <th>注文ステータス</th>
              <td class="d-flex align-items-center">
                <%= form_with(model: @order, url: admin_order_path(@order.id), local: true, class: "d-flex align-items-center") do |f| %>
                  <%= f.select :status, @order.class.statuses.keys.map { |k| [ @order.class.statuses_i18n[k], k ] }, 
                               { selected: @order.status }, class: "form-control form-control-sm mr-2" %>
                  <%= f.submit "更新" , class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
            </tr>
          </table>
        </div>

        <div class="col-md-5">
        </div>
      </div>
      
      <div class="row mt-4">
        
        <div class="col-md-8">
          <h4 class="mb-3">注文内容</h4>
          <table class="table table-bordered">
            <thead class="thead-light">
              <tr>
                <th style="width: 30%;">商品名</th>
                <th class="text-right">単価(税込)</th>
                <th class="text-right">数量</th>
                <th class="text-right">小計</th>
                <th style="width: 25%;">製作ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @order_details.each do |order_detail| %>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td class="text-right"><%= number_with_delimiter(order_detail.price) %></td>
                <td class="text-right"><%= order_detail.amount %></td>
                <td class="text-right"><%= number_with_delimiter(order_detail.amount * order_detail.price) %></td>
                <td>
                  <%= form_with(model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true, class: "d-flex align-items-center") do |f| %>
                    <%= f.select :making_status, order_detail.class.making_statuses.keys.map { |k| [ order_detail.class.making_statuses_i18n[k], k ] }, 
                                 { selected: order_detail.making_status }, class: "form-control form-control-sm mr-2" %>
                    <%= f.submit "更新" , class: "btn btn-success btn-sm" %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="col-md-4 mt-5">
          <table class="table table-sm table-borderless">
            <tr>
              <th class="text-right">商品合計</th>
              <td class="text-right"><%= number_with_delimiter(@order.total_payment) %>円</td>
            </tr>
            <tr>
              <th class="text-right">送料</th>
              <td class="text-right"><%= number_with_delimiter(@order.shipping_cost) %>円</td>
            </tr>
            <tr class="border-top border-dark">
              <th class="text-right font-weight-bold">請求金額合計</th>
              <td class="text-right font-weight-bold"><%= number_with_delimiter(@order.total_payment + @order.shipping_cost) %>円</td>
            </tr>
          </table>
        </div>
      </div>
      
    </div>
  </div>
</div>