config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  ## 会員側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get "about", to: "homes#about" #少し変更しました。headerボタンのため
    get 'addresses/index'
    get 'addresses/edit'
    resources :items, only: [:index, :show] do
      collection do
        get 'genre_search_result'
      end
    end
    # マイページ
    get "customers/my_page" => "customers#show"
    # 退会
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    # 情報編集
    get   "customers/information/edit" => "customers#edit"
    patch "customers/information"      => "customers#update"
    # 配送先
    resources :addresses, except: [:show]
    
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'destroy_all', on: :collection
    end
    
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        post 'thanks'
        get 'thanks'
      end
    end
  end

  ## 管理者側のルーティング設定
  namespace :admin do
    root to: "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, :address, :name, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 【ウッチャン追加】アソシエーション
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # 【ウッチャン追加】アソシエーション

  # customerの配送先
  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :image

    # 【ウッチャン追加】
    has_many :cart_items, dependent: :destroy
    # 【ウッチャン追加】
  
  enum status: { on_sale: 0, off_sale: 1 }#販売ステータス用enum

  with_options presence: true do
    validates :name
    validates :detail
    validates :price_without_tax
    validates :is_active
    validates :genre_id, presence: true
    validates :image
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, deposit_completed: 1, in_making: 2, preparing_for_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { making_unable: 0, waiting_for_making: 1, in_making: 2, making_completed: 3, }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# concerns/adminなどを使いますので、beforeaction
  protected

  def after_sign_in_path_for(resource)
    resource.is_a?(Admin) ? admin_root_path : root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin || resource_or_scope.is_a?(Admin)
      new_admin_session_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
  added = [
    :last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :phone_number
    ]
    devise_parameter_sanitizer.permit(:sign_up, keys: added)
    devise_parameter_sanitizer.permit(:account_update, keys: added)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash.html.erb
<%# keyとは メッセージの種類（例：notice, aleartなど） %>
<% flash.each do |key, msg| %>
  <% cls = case key.to_s
           when "notice" then "alert-success"
           when "alert"  then "alert-danger"
           else "alert-info"
           end %>
  <div class="alert <%= cls %>" role="alert"><%= msg %></div>
<% end %>

app/views/layouts/_footer.html.erb
<%# sticky footer　一番下に固定します(学習サイトみたいな感じです) %>
<footer class="border-top py-3">
  <div class="container text-center">
    <small>&copy; Copyright © 2025 Washoku Group All rights reserved. </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%# rescue "#" とは　もし問題なければroot_pathのurlへ移動、route設定ミスならblankページになります %>
    <%= link_to "Nakano Cake", (root_path rescue "#"), class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainNav">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item"><%= link_to "商品一覧", (admin_items_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ジャンル一覧", (admin_genres_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>

        <% elsif customer_signed_in? %>
          <li class="nav-item">
            <span class="navbar-text mr-3">
              ようこそ、<%= [current_customer&.last_name, current_customer&.first_name].compact.join(' ') %>さん！
            </span>
          </li>
          <li class="nav-item"><%= link_to "マイページ", (customers_my_page_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "商品一覧", (items_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "カート", cart_items_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link" %></li>

        <% else %>
          <li class="nav-item"><%= link_to "About", (about_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "商品一覧", (items_path rescue "#"), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nakano Cake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Google Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Funnel+Sans:wght@400;600&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">

    <%# Font Awesome %>
    <script src="https://kit.fontawesome.com/d31d06fbbc.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- sticky footer: flex column + main.flex-fill -->
  <body class="<%= ['d-flex','flex-column','min-vh-100', (content_for?(:body_class) ? yield(:body_class) : nil)].compact.join(' ') %>">
    <%= render "layouts/header" %>

    <main role="main" class="flex-fill py-4">
      <div class="container">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>